### ISSUE TITLE
period.tweenedLerp never removed

### ISSUE THREAD

**Issue by rbrisita** [domhofmann/PRTween#16]
When a PRTweenOperation expires it removes period.tweenedValue but not period.tweenedLerp. This is found on line 650 of PRTween.m.

**Comment by domhofmann** [comment]
Good finds on all of these. How much (if any) of your changes in your branch would you like to merge back? Don't wanna duplicate work and some of the changes look pretty good.

**Comment by rbrisita** [comment]
Well, I have changed the organization quite a bit and changed the infrastructure a little bit too. Basically, merging would add more files and take out the KVO and delayed calls. If you are open to it you can use what I have done, but I understand that developers have different organization and programming preferences. I have also added Doxygen documentation too. Let me know how you would like to proceed.

**Comment by domhofmann** [comment]
Yeah, I see that now.

I think I'll probably end up borrowing some of the code you've written for your branch. I'd like to add you to the contributor list if that's okay with you. Recently have had a lot of time to return to this library and turn it into what it needs to be. I plan on spending a lot more on it.

**Comment by rbrisita** [comment]
Sure, that would be great! I look forward to your changes. As for my branch development, I am at a content point, aka it's useful to me enough in my project, so I'll probably won't be updating it anytime soon.

**Comment by domhofmann** [comment]
Cool, will incorporate. Closing this ticket because it was fixed in a commit last night.
