### ISSUE TITLE
Add support for ARC

### ISSUE THREAD

**Issue by iheart2code** [domhofmann/PRTween#19]
First off -- great job building this one-line tweener for Obj-C. Coming from ActionScript, this makes things really easy for me.

I have been programming for iOS 5 and taking advantage of Automatic Reference Counting. I'd recommend maybe making available a branch or something that includes ARC support. If you'd be interested in my modified copy, I can send it.

**Comment by domhofmann** [comment]
This is a good idea. I've been using ARC myself and am getting tired of passing the flags to libs that I haven't yet ported. Can you share what you have?

**Comment by iheart2code** [comment]
I am more than willing to do that. However -- I'm not sure how. Am I able to push to the repo? Should I e-mail you my code?

**Comment by jwilling** [comment]
You're going to want to submit a pull request so @dominikhofmann can easily bring your changes into the main repo.  See a quick guide here: http://help.github.com/send-pull-requests/

**Comment by domhofmann** [comment]
Fixed in master! Thanks.
